apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler
spec:
  provider:
    doppler:
      project: snorlax
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            key: dopplerToken
            namespace: external-secrets
